# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-29 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_comment', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('emailAddress', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Edit_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_comment', models.CharField(max_length=250)),
                ('edit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_cmnts', to='user_dashboard.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='msg_entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_entered', to='user_dashboard.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_linked_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msgs_owned', to='user_dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmnt_entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmnts_entered', to='user_dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmnt_linked_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmnts_owned', to='user_dashboard.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='related_msg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_comments', to='user_dashboard.Message'),
        ),
    ]
